[
    {
        "specs": {},
        "ids": {},
        "original": [
            "/__w/splice-experiment-runs/splice-experiment-runs/first/lib64/python3.10/site-packages/libdnf/_error.so"
        ],
        "spliced": [
            "/__w/splice-experiment-runs/splice-experiment-runs/second/lib64/python3.10/site-packages/libdnf/_error.so"
        ],
        "paths": {},
        "predictions": {
            "symbols": [
                {
                    "splice_type": "different_lib",
                    "original_lib": "_error.so",
                    "spliced_lib": "_error.so",
                    "command": "missing-previously-found-symbols",
                    "message": [],
                    "prediction": true,
                    "seconds": 2.5510787963867188e-05
                },
                {
                    "splice_type": "different_lib",
                    "original_lib": "_error.so",
                    "spliced_lib": "_error.so",
                    "command": "missing-previously-found-exports",
                    "message": [],
                    "prediction": true,
                    "seconds": 6.9141387939453125e-06
                }
            ],
            "libabigail": [
                {
                    "message": "",
                    "return_code": 0,
                    "seconds": 0.00796365737915039,
                    "command": "/usr/local/bin/abidiff --debug-info-dir1 first/debug --debug-info-dir2 second/debug /__w/splice-experiment-runs/splice-experiment-runs/first/lib64/python3.10/site-packages/libdnf/_error.so /__w/splice-experiment-runs/splice-experiment-runs/second/lib64/python3.10/site-packages/libdnf/_error.so",
                    "spliced_lib": "/__w/splice-experiment-runs/splice-experiment-runs/second/lib64/python3.10/site-packages/libdnf/_error.so",
                    "original_lib": "/__w/splice-experiment-runs/splice-experiment-runs/first/lib64/python3.10/site-packages/libdnf/_error.so",
                    "prediction": true,
                    "splice_type": "different_lib"
                }
            ],
            "abi-laboratory": [
                {
                    "message": "old: /__w/splice-experiment-runs/splice-experiment-runs/first/lib64/python3.10/site-packages/libdnf/_error.so\nnew: /__w/splice-experiment-runs/splice-experiment-runs/second/lib64/python3.10/site-packages/libdnf/_error.so\nreport: /tmp/cache/__w/splice-experiment-runs/splice-experiment-runs/first/lib64/python3.10/site-packages/libdnf/_error.so-abi-laboratory-_error-so-_error-so.html\nERROR: missed debug-info file _error.so-0.66.0-1.fc36.x86_64.debug linked from gnu_debuglink (try --search-debuginfo=DIR option)\nERROR: can't find debug info in object(s)\nFound link to _error.so-0.66.0-1.fc36.x86_64.debug (gnu_debuglink)\n",
                    "return_code": 10,
                    "seconds": 0.08379769325256348,
                    "command": "/bin/bash /usr/bin/run_abi_laboratory.sh /__w/splice-experiment-runs/splice-experiment-runs/first/lib64/python3.10/site-packages/libdnf/_error.so /__w/splice-experiment-runs/splice-experiment-runs/second/lib64/python3.10/site-packages/libdnf/_error.so _error-so-_error-so /tmp/cache/__w/splice-experiment-runs/splice-experiment-runs/first/lib64/python3.10/site-packages/libdnf/_error.so-abi-laboratory-_error-so-_error-so.html",
                    "spliced_lib": "/__w/splice-experiment-runs/splice-experiment-runs/second/lib64/python3.10/site-packages/libdnf/_error.so",
                    "original_lib": "/__w/splice-experiment-runs/splice-experiment-runs/first/lib64/python3.10/site-packages/libdnf/_error.so",
                    "prediction": false,
                    "splice_type": "different_lib"
                }
            ]
        },
        "stats": {
            "sizes_bytes": {
                "/__w/splice-experiment-runs/splice-experiment-runs/first/lib64/python3.10/site-packages/libdnf/_error.so": 25608,
                "/__w/splice-experiment-runs/splice-experiment-runs/second/lib64/python3.10/site-packages/libdnf/_error.so": 25608
            }
        },
        "experiment": "_error-fedora-libs-35-fedora-libs-36",
        "result": "diff-libraries-present",
        "success": true,
        "splice": "/__w/splice-experiment-runs/splice-experiment-runs/second/lib64/python3.10/site-packages/libdnf/_error.so",
        "package": "/__w/splice-experiment-runs/splice-experiment-runs/first/lib64/python3.10/site-packages/libdnf/_error.so",
        "different_libs": true
    }
]